import type { Item } from "./models";

export const mockItems: Item[] = [
  {
    id: "1",
    sku: "SUP-HOOD-001",
    brand: "Supreme",
    name: "Box Logo Hoodie FW18",
    category: "Hoodie",
    size: "L",
    condition: "9/10",
    colorway: "Grey/Red",
    cost: 450,
    listPrice: 750,
    status: "available",
    images: ["/mock/supreme-box-logo-hoodie.jpg"],
    acquisitionDate: "2024-11-01",
    notes: "Very clean, minimal cracking on box logo.",
  },
  {
    id: "2",
    sku: "BAPE-TEE-003",
    brand: "BAPE",
    name: "College Logo Tee",
    category: "Tee",
    size: "M",
    condition: "8/10",
    colorway: "White/Green",
    cost: 80,
    listPrice: 140,
    status: "available",
    images: ["/mock/bape-college-tee.jpg"],
    acquisitionDate: "2024-10-20",
    notes: "Slight fading from washes.",
  },
  {
    id: "3",
    sku: "GDEPT-JEANS-010",
    brand: "Gallery Dept",
    name: "Flared Denim",
    category: "Jeans",
    size: "32",
    condition: "9/10",
    colorway: "Indigo",
    cost: 650,
    listPrice: 1100,
    status: "reserved",
    images: ["/mock/gallery-dept-jeans.jpg"],
    acquisitionDate: "2024-09-05",
    notes: "Reserved for VIP client, holding until 2025-01-15.",
  },
];

